package ir.mat.project;

import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author mat
 */
public class activity_main extends javax.swing.JFrame {

    private DefaultMutableTreeNode root;

    private String path;
     
    private File DirCh;
    
    private DefaultTreeModel treeModel;
   
    /**
     * Creates new form activity_main
     */
    public activity_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        MoveItemButton = new javax.swing.JButton();
        MoveItems = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notepad");
        setBackground(new java.awt.Color(153, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1382, 900));

        jPanel1.setPreferredSize(new java.awt.Dimension(1382, 900));

        jTree1.setToolTipText("");
        jTree1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTree1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        jTree2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jTree2MouseDragged(evt);
            }
        });
        jTree2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTree2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTree2MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTree2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTree2MouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTree2);

        jLabel1.setText("Root");

        jLabel2.setText("projects");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList1);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList2);

        MoveItemButton.setPreferredSize(new java.awt.Dimension(30, 30));
        MoveItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveItemButtonActionPerformed(evt);
            }
        });

        MoveItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveItemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MoveItems, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(MoveItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1122, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addGap(18, 18, 18)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MoveItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(MoveItems, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(426, 426, 426))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(404, 404, 404)))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(94, 94, 94)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        jMenuBar1.setBackground(new java.awt.Color(87, 165, 255));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 255));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(66, 40));

        jMenu1.setBackground(new java.awt.Color(102, 153, 255));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Open Dir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator3);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setText("New Project");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setText("Save");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator2);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("close");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(102, 153, 255));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Edit");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1392, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        //Build new project through NewProject class.
        NewProject dialog = new NewProject();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        dialog.setTitle("New Project");
        dialog.Actions();
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        //Open the Tank file in the tree
        FileChooser f = new FileChooser();
        ChangeDirTreeAddress(f.Chooser(Global.DirectoryRootAddress));
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void MoveItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveItemsActionPerformed
        
        System.out.println("******* File's Name *******");
        System.out.println(Global.TextFilesName.size());
        for(int i = 0 ; i<=Global.TextFilesName.size()-1 ; i++)
        {
            System.out.println(Global.TextFilesName.get(i));
        }
        
        
        String[] paths;
        String[] TextFileName;
        
        paths = Global.Jtree1PathArray.toArray(new String[Global.Jtree1PathArray.size()]);
        
        TextFileName = Global.TextFilesName.toArray(new String[Global.TextFilesName.size()]);

        if(Global.ItemSelectedFlagTree2 == 1 && Global.DirectoryRootAddress != "")
        {
            
        String dirTo = Global.DirectoryOfProjectsAddress + "\\"+ jTree2.getLeadSelectionPath().getLastPathComponent().toString();

        try {
            CopyFile.copyFiles(paths,TextFileName, dirTo);
            System.out.println("\nFiles moved successfully!");
        } catch (IOException ex) {
            Logger.getLogger(activity_main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        ChangeProjectTreeAddress();

        
            
        }
        if(Global.ItemSelectedFlagTree2 == 0)
        JOptionPane.showMessageDialog(null, "Please select a project file!");

    }//GEN-LAST:event_MoveItemsActionPerformed

    private void MoveItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveItemButtonActionPerformed

        //Check the file type selected in the tree
        String TypeCheck = "";
        if(Global.DirectoryRootAddress != "" && Global.ItemSelectedFlagTree1 == 1)
        {
            TypeCheck = getFileExtension.getFileExtension(jTree1.getLeadSelectionPath().getLastPathComponent().toString());
        }

        //Copy the file to the selected project
        if(Global.ItemSelectedFlagTree1 == 1 && Global.ItemSelectedFlagTree2 == 1 && TypeCheck.equals("txt"))
        {

            File dirFrom = new File(Global.SelectedJtree1ItemAdress);
            File dirTo = new File(Global.DirectoryOfProjectsAddress + "\\"+ jTree2.getLeadSelectionPath().getLastPathComponent().toString()+ "\\"+ jTree1.getLeadSelectionPath().getLastPathComponent().toString());

                try {
                    //copyFile is a method in copyFile.class
                    CopyFile.copyFile(dirFrom, dirTo);
                    System.out.println("File moved successfully");
                    ChangeProjectTreeAddress();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error!");
                }

            }
            else{

                if(Global.ItemSelectedFlagTree1 == 0)
                JOptionPane.showMessageDialog(null, "Please insert a Directory And Choose .txt file!");
                else
                if(!TypeCheck.equals("txt"))
                JOptionPane.showMessageDialog(null, "Only a file with .txt type must be selected");
                else
                if(Global.ItemSelectedFlagTree2 == 0)
                JOptionPane.showMessageDialog(null, "Please select a project file!");

            }
    }//GEN-LAST:event_MoveItemButtonActionPerformed

    private void jTree2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseReleased

    }//GEN-LAST:event_jTree2MouseReleased

    //Open the file after double clicking on the tree node
    private void jTree2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MousePressed
        int selRow = jTree2.getRowForLocation(evt.getX(), evt.getY());
        TreePath selPath = jTree2.getPathForLocation(evt.getX(), evt.getY());
        if(selRow != -1) {
            if(evt.getClickCount() == 1) {
                Global.ItemSelectedFlagTree2 = 1;
            }
            else if(evt.getClickCount() == 2) {
                //Open Tab
                path = Global.DirectoryOfProjectsAddress + "\\" +
                jTree2.getLeadSelectionPath().getPathComponent(WIDTH).toString() + "\\" +
                jTree2.getLeadSelectionPath().getLastPathComponent().toString();
                //Call the class to add tab
                DirCh = new File(this.path);
                if(DirCh.exists())
                {
                    System.out.println(path);

                    AddTabToTabbedPane.mat(path,jTree2.getLeadSelectionPath().getLastPathComponent().toString());

                    CustomTabbedPane.CloseButton.setIcon(new ImageIcon(Class.class.getResource("/res/exitbutton.png")));
                }

            }
        }
    }//GEN-LAST:event_jTree2MousePressed

    private void jTree2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseEntered
        ExpandJtree2Nodes();
    }//GEN-LAST:event_jTree2MouseEntered

    private void jTree2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseClicked

        //Catch the flag to confirm the selection of a node
        Global.ItemSelectedFlagTree2 = 1;
    }//GEN-LAST:event_jTree2MouseClicked

    private void jTree2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree2MouseDragged

    }//GEN-LAST:event_jTree2MouseDragged

    private void jTree1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseEntered

    }//GEN-LAST:event_jTree1MouseEntered

    private void jTree1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTree1MouseClicked
        doMouseClicked(evt);
    }//GEN-LAST:event_jTree1MouseClicked

    
    public static void main(String mat[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(activity_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(activity_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(activity_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(activity_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new activity_main().setVisible(true);
                

            }
        });
        
    }

    
    //Make the selected file address of the first tree
    static void  doMouseClicked(MouseEvent me) {
    
    try {
          Global.SelectedJtree1ItemAdress = Global.DirectoryRootAddress + "\\" + jTree1.getLeadSelectionPath().getLastPathComponent().toString() ; 

    } catch (Exception e) {
          System.out.println("Clicked On Jtree1!");
    }
          Global.ItemSelectedFlagTree1 = 1;
          System.out.println(Global.SelectedJtree1ItemAdress);

}
        
    
    
    public void ChangeDirTreeAddress(String root)
    {
      
      //set root for jtree1
      ChangeTreeAddress change = new ChangeTreeAddress(root , 1);
      
      //remove all elements of Path Array
      Global.Jtree1PathArray.clear();
      
      //remove all elements of TextFilesName Array
      Global.TextFilesName.clear();
      
      //Create an array of first tree files
      MakePathArray.visitAllNodes(jTree1);
        
      //Sort the file array
      MakePathArray.SortArray();

           
    }
     
    public void ChangeProjectTreeAddress()
    {
      //set root for jtree2
        ChangeTreeAddress change = new ChangeTreeAddress(Global.DirectoryOfProjectsAddress , 2);
    }
   
    public static void ExpandJtree2Nodes()
    {
        // Expand Jtree2 nodes with invoke the method of ExpandAllNodes.class . 
        ExpandAllNodes ean = new ExpandAllNodes();
        ean.expandTree(jTree2 , true);

    }
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton MoveItemButton;
    public static javax.swing.JButton MoveItems;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JList<String> jList1;
    public static javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public static javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTree jTree1;
    public static javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables




}


